### ISSUE TITLE
Ignore all binary files from check

### ISSUE THREAD

**Issue by janhelke** [editorconfig-checker/editorconfig-checker.php#102]
You can't check them anyway and that would mitigate the issue to add a new extension every time a new kind of file is included in a web project.

**Comment by mstruebing** [comment]
There is already a new version in the working: https://github.com/editorconfig-checker/editorconfig-checker.go

This will do exactly what you are saying, it's focused on usability but I'm not finished yet to release the first stable version.

Hint: The php/js/<or any other language> will then be a wrapper for the golang version. :)

**Comment by mstruebing** [comment]
@janhelke if you want you could already try out the golang version: https://github.com/editorconfig-checker/editorconfig-checker/releases/tag/0.0.3

I will write a wrapper for php soonish

**Comment by mstruebing** [comment]
Closing as the `7.x`-branch is no longer actively maintained.
