### ISSUE TITLE
Make the usage of --exclude and --ignore-defaults cumulative

### ISSUE THREAD

**Issue by janhelke** [editorconfig-checker/editorconfig-checker.php#103]
Currently if you use --exclude and --ignore-defaults together, all settings from Utilities::defaults are ignored. So ... the setting is ignored, not the content of the setting ... bah. You will see the issue, if you try to reproduce it :-)

**Comment by mstruebing** [comment]
Closing as the `7.x`-branch is no longer actively maintained.
