### ISSUE TITLE
Invalid path prefix while running it in Docker

### ISSUE THREAD

**Issue by Dgame** [editorconfig-checker/editorconfig-checker.php#150]
Hi, nice project, but it doesn't seem to work as described when running the project in a Linux Docker environment. I get the following error:

> editorconfig-checker
/var/www/html/vendor/editorconfig-checker/editorconfig-checker/bin/editorconfig-checker: line 2: .//var/www/html/vendor/editorconfig-checker/editorconfig-checker/bin/ec: No such file or directory

The problem is the leading `./` but I don't know where it comes from. If I run `/var/www/html/vendor/editorconfig-checker/editorconfig-checker/bin/ec` it works just fine.

I am using WSL on Windows 10, Docker environment is running under WSL.

**Comment by mstruebing** [comment]
Hey thank you for that issue.

Could you give me a minimal reproducible example of your Dockerfile/image you are running on?
Also: could you try to check if the same happens when you use https://github.com/editorconfig-checker/editorconfig-checker directly without the PHP wrapper?

**Comment by ktomk** [comment]
@Dgame Can you add the first version the issue appeared to you and additionally test if it still happens with the latest version?

And are symbolic links in use? ./ may suggest that but details of your setup aren't visible enough for me to know that.

If so, are those created on Windows or WSL side or both?

**Comment by Dgame** [comment]
Hey, I don't use this as it didn't work and I didn't want to waste too much time. I use a couple of other style checkers that work well, so I don't have a need for this anymore - which means my configurations are long gone and I can't say for sure which version it was that I was testing (I suspect the latest version at the time). But there were no symbolic links involved, and yes I originally created it in WSL, but that shouldn't make any difference as all the setup was done in WSL.

So from my side, the issue can be closed :) Keep up the good work!

**Comment by ktomk** [comment]
Well fine then and thanks for the update. Please close the issue as it's not reproducible any longer.
