### ISSUE TITLE
Support ARM architecture

### ISSUE THREAD

**Issue by janedbal** [editorconfig-checker/editorconfig-checker.php#164]
When running analysis on ARM arch, analysis fails [here](https://github.com/editorconfig-checker/editorconfig-checker.php/blob/master/src/EditorconfigChecker/Utilities.php#L20). Can you add support for it? `php_uname('m')` returns `aarch64` on ARM.

**Comment by mstruebing** [comment]
Could you please test this PR? https://github.com/editorconfig-checker/editorconfig-checker.php/pull/165

(I can not)
