### ISSUE TITLE
Nicer output of errors (sort by filename, be less verbose)

### ISSUE THREAD

**Issue by pixelbrackets** [editorconfig-checker/editorconfig-checker.php#32]
(Feature Request, nice tool btw)

It would be nice if the tool could group the errors to enhance readability if a lot of errors occur. For example like in the log of the popular »php-cs-fixer«.

Bonus: Be less verbose. Only show detailed errors if a verbose flag was given.

Example:

    $> editorconfig-checker ./*
    ........F....F.F...
    
    1) acme/file.txt (amount of spaces, trailing whitespace)
    2) acme/foo.php (indentation type)
    3) acme/kermit.txt (indentation type)
    
    19 files checked, 167 errors occured
    Check log above and fix the issues.

And more verbose:

    $> editorconfig-checker -v ./*
    ........F....F.F...
    
    1) acme/file.txt (amount of spaces, trailing whitespace)
       Amount of spaces on line 256
       Amount of spaces on line 257
       Trailing whitespace on line 257
       Amount of spaces on line 258
    2) acme/foo.php (indentation type)
       Indentation types on line 1
       Indentation types on line 2
       Indentation types on line 3
       Indentation types on line 4
    3) acme/kermit.txt (indentation type)
       Indentation types on line 4
       Indentation types on line 8
       Indentation types on line 15
       Indentation types on line 16
       Indentation types on line 23
       Indentation types on line 42
    
    19 files checked, 167 errors occured
    Check log above and fix the issues.

**Comment by mstruebing** [comment]
Thanks for you feedback I really appreciate it. In fact I had considered a general verbose flag too, so I would think you will get this feature soon.

**Comment by mstruebing** [comment]
Closed by #36
