### ISSUE TITLE
Exclude parameter ignores dots

### ISSUE THREAD

**Issue by pixelbrackets** [editorconfig-checker/editorconfig-checker.php#33]
The ReadMe lists a code example to ignore filetypes/names.

    vendor/somefile.php
    .txt/config.yml
    txt/foo.php
    acme/abctxt/foo.txt
    bar.php
    bar.txt

Run `editorconfig-checker -d -e 'vendor|.txt' ./*`

Expected: Check `txt/foo.php`, `acme/abctxt/foo.txt`, `bar.php`, ignore all other (like the `.txt` folder or files ending with `.txt`)

Actual result: Only checks `bar.php`, because the dot is ignored.

I use editorconfig-checker 4.1.0 on Ubuntu 16.04.

**Comment by pixelbrackets** [comment]
Ah, see `getExcludedPatternFromOptions` & `filterFiles` in »editorconfig-checker/src/EditorconfigChecker/Cli/Cli.php«.

All exclude parameters are _always_ converted into a regex pattern. They are then always used in a »preg_match« function. This means, that dots are interpreted as [»any single character«](http://php.net/manual/de/function.preg-match.php#105924). So excluding ».txt« wont “filter all files which has .txt in their name” but “filter all files which has txt in their name” instead.

Solution: Escape all special regex characters, eg. `-e '\.txt'`.

Escaping must always be done in quotes however. Using `-e \.txt` would escape the character in the shell already and then just pass ».txt« to the script.

Suggestion:
* Update all examples, escape the dot 
* Add a hint to the help text (“string or regex to filter files which should not be checked“ should be something like »regex to filter files which should not be checked, wrap in quotes to escape special characters«)

**Comment by mstruebing** [comment]
Thanks again.
I will update the readme asap.
If you encounter any other bugs please let me know - also there would be no problem(if you have the time to of course) to merge a pull request from you if you would fix it ;)
