### ISSUE TITLE
Fix Task

### ISSUE THREAD

**Issue by pixelbrackets** [editorconfig-checker/editorconfig-checker.php#38]
Some errors are easy to fix, eg. »Missing final newline«. It would be cool if the tool may do these easy fixes itself.

**Comment by mstruebing** [comment]
What flag would you suggest to fix `fixable` errors automatically? 
Intuitive would be `f` for `fix` but it is already used from `files` - which I think is a good flag to check if all files get checked I want to.

I would think about `a` for `auto-fix`.
WDYT?

**Comment by pixelbrackets** [comment]
»auto-fix« sounds good to me.

PS: Imho »f« is mostly used as alias for »force« in bash, so imho »list-files« is better. Buts thats just nitpicking ;)

**Comment by mstruebing** [comment]
I like nitpicking because I'm mostly unsure about what am I doing and then end up with just some stuff I think is right :+1: 

I can find some time after this week is done to start working on the open issues :)
