### ISSUE TITLE
Absolute vs. Relative File Glob

### ISSUE THREAD

**Issue by pixelbrackets** [editorconfig-checker/editorconfig-checker.php#49]
(moved from #45)

I have a general remark about this, since this filepath issue popped up several times. The script currently expects a relative filepath / file glob. The script then searches for all matching files and stores a list of relativ filenames.

The rule getter then builds an absolute path using the the starting point of the current CLI script and the filename. This path is used to get the .editorconfig. But since this is generated it may not be real (eg. due to funny symlinks or path combinations). Or it will return wrong results if the given file glob is absolute instead of relative.

I've had this issue and tried to build a working fallback. But had no satisfying result after several hours. So I'll write down my ideas, maybe you have a better/faster solution.

**A)** Catch the type of the file glob and _always_ generate the list of files with absolute links only.

Old:
Run `bin/editorconfig-checker test-folder/*` to get filelist `test-folder/test/testfile.php`. Calculate root path `/home/johndoe/git/editorconfig`. Normalize filelist. Build new filepath `/home/johndoe/git/editorconfig/test-folder/test/testfile.php` in rule getter and search for the editorconfig file.

New: 
Run `bin/editorconfig-checker test-folder/*` to get filelist `/home/johndoe/git/editorconfig/test-folder/test/testfile.php`. The rule getter now uses the existing filepath only and does not need to guess a path again. This reduces possible failure points, since all methods always use the same path 
Bonus: The `-l` param will return the full filepath, which is easier to debug (the rule getter method is silent for users).

I tried to get an absolute path, regardless of whether the user gives a relative or absolute file glob. Got no working solution, one of both file globs always returned not satisfying results. :-/

As an alternative I tried out the [Simfony File Finder](https://symfony.com/doc/current/components/finder.html). This package is able to do the relative and absolute file path juggling and always return absolute filenames :

`src/EditorconfigChecker/Cli/Cli.php` → `getFileNames()`

            $finder = new \Symfony\Component\Finder\Finder();
            $finder->files()->in($fileGlob);
            foreach ($finder as $file) {
                print_r(['symfonyFileGlob' => $file->getRealPath()]);
            }

Using this component would require a rewrite of the exclude mechanism however. 

**B)** Require absolute file globs only (my favourite).

This is behaviour is used by several CLI tools. I guess exactly because they want to avoid these issues with relative paths. 

See editorconfig CLI:

https://github.com/editorconfig/editorconfig/wiki/FAQ#the-executable-of-editorconfig-core-does-not-accept-relative-paths-how-can-i-fix-that

> Since EditorConfig core executables are usually not supposed to be called by humans from command line, we did not support relative paths for simplicity across all implementations of EditorConfig cores. 

Also add a note about using absolute file globs only to the `Readme` and CLI Help Screen (and since this would break existing installations, add it to the release notes of a new mayor version).

Note that it is still possible to run relative file globs with a trick. Use a path variable. Run `bin/editorconfig-checker $(pwd)/test-folder/*`, the variable will be expanded to the absolute path automatically.

**C)** Catch if the file glob is using an absolute filepath. If so break and return an exception. Also add a note about using relative file globs only to the `Readme` and CLI Help Screen. The problems described above (path guessing in rule getter method) then still exist though.

**Comment by pixelbrackets** [comment]
Stumbled upon this issues again today on a machine.

`cd /tmp/foo/ && /usr/local/bin/editorconfig /srv/bar/baz/*` checks all files in `/srv/bar/baz/`, but uses a  `.editorconfig` file located in `/tmp/foo/`, instead of `/srv/bar/baz/`.

This is especially confusing because the EditorConfig Checker is supposed to search for an `.editorconfig` file along the rootline (check file `/srv/bar/baz/acme/somefile.php` → look for `.editorconfig` with `root-flag in `/srv/bar/baz/acme/`, `/srv/bar/baz/`, `/srv/bar/`, `/srv/`.

**Comment by mstruebing** [comment]
Closing as the `7.x`-branch is no longer actively maintained.
