### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by s2b** [editorconfig-checker/editorconfig-checker.php#52]
When I forgot to exclude node_modules in my editorconfig linting command, the following PHP notices occurred:

> Notice: Uninitialized string offset: 2 in /Users/simon/Projekte/medac-relaunch/vendor/editorconfig-checker/editorconfig-checker/src/EditorconfigChecker/Validation/IndentationValidator.php on line 55
> PHP Notice:  Uninitialized string offset: 2 in /Users/simon/Projekte/medac-relaunch/vendor/editorconfig-checker/editorconfig-checker/src/EditorconfigChecker/Validation/IndentationValidator.php on line 55

**Comment by mstruebing** [comment]
I think this is not needed anymore with default excludes.
