### ISSUE TITLE
Filteextension to add to default excludes

### ISSUE THREAD

**Issue by mstruebing** [editorconfig-checker/editorconfig-checker.php#70]
Every suggestion is welcome. 

Currently in my mind:

`pdf`
`jpeg`
`.DS_Store`

Added.
Additional suggestions are welcome

**Comment by mimmi20** [comment]
Suggestions
- png|gif|zip|tar
- all files in an existing .gitignore file

**Comment by mstruebing** [comment]
Thank you, my plan is to introduce ignoring based on gitignore for the next major.
Help is always appreciated. :)

**Comment by mstruebing** [comment]
Closing as the `7.x`-branch is no longer actively maintained.
